# Flash Loan Configuration
FLASH_LOAN:
  CONTRACT_ADDRESS: "0xE0C08c66BD0e54338eD3f15608eeEe2a2B36efe2"
  # MIN_PROFIT: 0.01
  # GAS_MULTIPLIER: 1.2
  ABI:
    - "function uniswapV2Call(address sender, uint256 amount0, uint256 amount1, bytes calldata data) external"
    - "function withdrawToken(address token, uint256 amount) external"
    - "function owner() external view returns (address)"
    - "event ArbitrageExecuted(uint256 profit, uint256 timestamp)"

# Bot Settings
BOT_SETTINGS:
  MIN_PROFIT_THRESHOLD: 0.5
  MAX_GAS_PRICE: 1000
  SLEEP_TIME: 1000

# Network Configuration
network:
  rpc:
    - "https://polygon-rpc.com"
    - "https://rpc-mainnet.matic.network"
    - "https://rpc-mainnet.maticvigil.com"

# Contract Addresses
addresses:
  AAVE_V3_POOL: "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
  AAVE_V2_POOL: "0x8dFf5E27EA6b7AC08EbFdf9eB090F32ee9a30fcf"
  WMATIC: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
  WETH: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
  USDC: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
  USDT: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
  WBTC: "0x1BFD67037B42Cf73acF2047067bd4F2C47D9BfD6"

# DEX Configuration
dexes:
  factories:
    UniswapV3: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
    QuickSwap: "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
    SushiSwap: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
    ApeSwap: "0xCf083Be4164828f00cAE704EC15a36D711491284"
    JetSwap: "0x668ad0ed2622C62E24f0d5ab6B6Ac1b9D2cD4AC7"

  routers:
    UniswapV3: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
    QuickSwap: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
    SushiSwap: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
    ApeSwap: "0xC0788A3aD43d79aa53B09c2EaCc313A787d1d607"
    JetSwap: "0x5C6EC38fb0e2609672BDf628B1fD605A523E5923"

# Trading Parameters
tradingParameters:
  minProfitThreshold: 0.0003    # Base minimum profit
  maxSlippage: 1.0              # Maximum 1% slippage
  gasLimit: 300000
  maxGasPrice: 50               # Maximum gas price in gwei
  profitMarginBuffer: 1.2       # Multiply expected costs by 1.2x for safety
  minProfitUSD: 5.0            # Minimum profit in USD

  # Gas price thresholds (in gwei)
  gasThresholds:
    veryLow: 30
    low: 40
    medium: 50
    high: 70
    veryHigh: 100

# Trading Pairs with amounts
tradingPairs:
  - name: "WETH/USDC"
    token0Symbol: "WETH"
    token1Symbol: "USDC"
    token0Address: "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: ".1"
    minTradeAmount: "0.01"

  - name: "MATIC/USDC"
    token0Symbol: "MATIC"
    token1Symbol: "USDC"
    token0Address: "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "5000"
    minTradeAmount: "100"

  - name: "QUICK/USDC"
    token0Symbol: "QUICK"
    token1Symbol: "USDC"
    token0Address: "0x831753DD7087CaC61aB5644b308642cc1c33Dc13"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "50"
    minTradeAmount: "1"

  - name: "GHST/USDC"
    token0Symbol: "GHST"
    token1Symbol: "USDC"
    token0Address: "0x385Eeac5cB85A38A9a07A70c73e0a3271CfB54A7"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "1000"
    minTradeAmount: "50"

  - name: "LINK/USDC"
    token0Symbol: "LINK"
    token1Symbol: "USDC"
    token0Address: "0x53E0bca35eC356BD5ddDFebbD1Fc0fD03FaBad39"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "200"
    minTradeAmount: "10"

  - name: "SAND/USDC"
    token0Symbol: "SAND"
    token1Symbol: "USDC"
    token0Address: "0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "2000"
    minTradeAmount: "100"

  - name: "BAL/USDC"
    token0Symbol: "BAL"
    token1Symbol: "USDC"
    token0Address: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
    token1Address: "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
    token0Decimals: 18
    token1Decimals: 6
    maxTradeAmount: "100"
    minTradeAmount: "5"
